version: '3'


services:
  django: &django
    depends_on:
      - postgres
      - mailhog
  docs:
    image: rec_demo_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./rec_demo:/app/rec_demo:z
    ports:
      - "7000:7000"
    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  celeryworker:
    depends_on:
      - redis
      - postgres
      - mailhog


  celerybeat:
    <<: *django
    image: rec_demo_local_celerybeat
    container_name: celerybeat
    depends_on:
      - redis
      - postgres
      - mailhog
    ports: []
    command: /start-celerybeat
#
#  flower:
#    <<: *django
#    image: rec_demo_local_flower
#    container_name: flower
#    ports:
#      - "5555:5555"
#    command: /start-flower
