# Generated by Django 3.0.11 on 2021-01-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_auto_20210105_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='broker',
            options={'verbose_name': 'Broker', 'verbose_name_plural': 'Brokers'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'Contract', 'verbose_name_plural': 'Contracts'},
        ),
        migrations.AlterModelOptions(
            name='realestateproject',
            options={'verbose_name': 'Real estate project', 'verbose_name_plural': 'Real estate projects'},
        ),
        migrations.AlterModelOptions(
            name='realestatespace',
            options={'verbose_name': 'Real estate space', 'verbose_name_plural': 'Real estate spaces'},
        ),
        migrations.AddField(
            model_name='company',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='contract',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='real_estate.Broker', verbose_name='Broker'),
        ),
        migrations.AddField(
            model_name='realestateproject',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
