# Generated by Django 3.0.11 on 2021-01-10 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_auto_20210110_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contractclient',
            options={'ordering': ('is_principal',)},
        ),
        migrations.AlterModelOptions(
            name='realestatespace',
            options={'ordering': ('project__name', 'space_type', 'name'), 'verbose_name': 'Real estate space', 'verbose_name_plural': 'Real estate spaces'},
        ),
    ]
